// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SweatSheet.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240413084848_newDb1")]
    partial class newDb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("SweatSheet.Server.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryMuscleGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseTitle = "Bench Press",
                            PrimaryMuscleGroup = 0
                        },
                        new
                        {
                            Id = 2,
                            ExerciseTitle = "Pull Ups",
                            PrimaryMuscleGroup = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseTitle = "Shoulder Press",
                            PrimaryMuscleGroup = 2
                        });
                });

            modelBuilder.Entity("SweatSheet.Server.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalWeightWorkout")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutDurationInSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2024, 4, 13, 12, 48, 48, 633, DateTimeKind.Local).AddTicks(5212),
                            StartTime = new DateTime(2024, 4, 13, 11, 48, 48, 633, DateTimeKind.Local).AddTicks(5205),
                            Title = "Workout 1",
                            TotalWeightWorkout = 0.0,
                            WorkoutDurationInSeconds = 3600
                        });
                });

            modelBuilder.Entity("SweatSheet.Server.WorkoutActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalWeightActivity")
                        .HasColumnType("REAL");

                    b.Property<int?>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("SweatSheet.Server.WorkoutActivity", b =>
                {
                    b.HasOne("SweatSheet.Server.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.HasOne("SweatSheet.Server.Workout", null)
                        .WithMany("Activities")
                        .HasForeignKey("WorkoutId");

                    b.OwnsMany("SweatSheet.Server.ActivitySet", "Sets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ActivityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Reps")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Weight")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("ActivityId");

                            b1.ToTable("ActivitySet");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.Navigation("Exercise");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("SweatSheet.Server.Workout", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
